import { App, MarkdownRenderer, Component, setIcon } from 'obsidian';
import { ToolAction } from '../types';

export class MessageRenderer {
  app: App;
  container: HTMLElement;

  constructor(app: App, container: HTMLElement) {
    this.app = app;
    this.container = container;
  }

  renderTo(container: HTMLElement) {
    this.container = container; // Allow rebinding
  }

  async renderUserMessage(msg: import('../types').ChatMessage, avatarUrl: string) {
    const text = msg.parts?.[0]?.text || '';
    const msgBlock = this.container.createDiv('chat-message-block message-block-user');
    const avatar = msgBlock.createEl('img', { cls: 'chat-avatar', attr: { src: avatarUrl } });
    const msgEl = msgBlock.createDiv('chat-message message-user');
    msgEl.innerText = text;
    this.scrollBottom();
    return msgEl;
  }

  async renderAIMessage(msg: import('../types').ChatMessage, avatarUrl: string) {
    const msgBlock = this.container.createDiv('chat-message-block message-block-ai');
    // Store role for updates
    msgBlock.dataset.role = 'model';

    const avatar = msgBlock.createEl('img', { cls: 'chat-avatar', attr: { src: avatarUrl } });
    const contentContainer = msgBlock.createDiv('chat-message-content message-ai');

    // 1. Tool Actions
    const actionContainer = contentContainer.createDiv('chat-tool-actions');
    if (msg.actions && msg.actions.length > 0) {
      await this.renderToolActions(actionContainer, msg.actions);
    }

    // 2. Thinking Block
    const thinkingContainer = contentContainer.createDiv('thinking-container');
    thinkingContainer.style.display = 'none'; // Default hidden

    const thinkingHeader = thinkingContainer.createDiv('thinking-header');
    setIcon(thinkingHeader.createSpan('thinking-icon'), 'brain-circuit');
    thinkingHeader.createSpan().innerText = 'Thinking Process';

    const thinkingContent = thinkingContainer.createDiv('thinking-content');

    if (msg.thinking) {
      thinkingContainer.style.display = 'block';
      thinkingContent.innerText = msg.thinking;
      thinkingContainer.addClass('thinking-code-block');
    }

    // 3. Response Text
    const textContainer = contentContainer.createDiv('chat-text-content');
    const text = msg.parts?.[0]?.text || '';

    if (text) {
      const component = new Component();
      component.load();
      await MarkdownRenderer.render(this.app, text, textContainer, '', component);
    }

    // 4. Model Chip
    const footerEl = contentContainer.createDiv('model-footer-chip');
    if (msg.model) {
      footerEl.innerText = `Generated by ${msg.model}`;
      footerEl.title = "This model was automatically selected based on your prompt complexity.";
      footerEl.style.display = 'block';
    } else {
      footerEl.style.display = 'none';
    }

    this.scrollBottom();
    return contentContainer;
  }

  /**
   * Updates an existing message DOM element with new data (Streaming).
   */
  async updateMessage(dom: HTMLElement, msg: import('../types').ChatMessage, avatarUrl: string) {
    const contentContainer = dom.querySelector('.chat-message-content') as HTMLElement;
    if (!contentContainer) return; // Should not happen for AI messages

    // 1. Tool Actions
    let actionContainer = contentContainer.querySelector('.chat-tool-actions') as HTMLElement;
    if (!actionContainer) actionContainer = contentContainer.createDiv('chat-tool-actions');

    // We could be smarter about diffing actions, but re-rendering chips is cheap enough
    if (msg.actions && msg.actions.length > 0) {
      actionContainer.empty();
      await this.renderToolActions(actionContainer, msg.actions);
    }

    // 2. Thinking
    let thinkingContainer = contentContainer.querySelector('.thinking-container') as HTMLElement;
    if (!thinkingContainer) {
      // If it didn't exist (e.g. streaming started without thinking)
      thinkingContainer = contentContainer.createDiv('thinking-container');
      // Re-create header
      const thinkingHeader = thinkingContainer.createDiv('thinking-header');
      setIcon(thinkingHeader.createSpan('thinking-icon'), 'brain-circuit');
      thinkingHeader.createSpan().innerText = 'Thinking Process';
      thinkingContainer.createDiv('thinking-content');
    }

    const thinkingContent = thinkingContainer.querySelector('.thinking-content') as HTMLElement;

    if (msg.thinking) {
      thinkingContainer.style.display = 'block';
      // Typewriter / Update check
      if (thinkingContent.innerText !== msg.thinking) {
        thinkingContent.innerText = msg.thinking;
        thinkingContainer.addClass('thinking-code-block');
        // Auto-scroll thinking
        thinkingContent.scrollTop = thinkingContent.scrollHeight;
      }
    } else {
      thinkingContainer.style.display = 'none';
    }

    // 3. Text
    let textContainer = contentContainer.querySelector('.chat-text-content') as HTMLElement;
    if (!textContainer) textContainer = contentContainer.createDiv('chat-text-content');

    const text = msg.parts?.[0]?.text || '';

    // Only re-render if text changed length significantly or is finalizing
    // For proper typewriter, we'd append text node chars.
    // MarkdownRenderer is heavy, so we might want to just set innerText for streaming and MD for final?
    // Or just re-render. MarkdownRenderer is reasonably fast for small chunks.
    // Let's rely on simple re-render for now, user asked for Typewriter.
    // Implementing TRUE Typewriter with Markdown is hard because MD structure changes.
    // We will render Full MD.

    if (textContainer.innerText !== text) { // Naive check, innerText strips formatting
      // Actually, we should check raw text length to decide to update
      const component = new Component();
      component.load();
      textContainer.empty(); // Clear previous MD
      await MarkdownRenderer.render(this.app, text, textContainer, '', component);

      // Scroll chat to bottom
      this.scrollBottom();
    }

    // 4. Model Chip
    let footerEl = contentContainer.querySelector('.model-footer-chip') as HTMLElement;
    if (!footerEl) footerEl = contentContainer.createDiv('model-footer-chip');

    if (msg.model) {
      footerEl.innerText = `Generated by ${msg.model}`;
      footerEl.style.display = 'block';
    }
  }


  startAIMessage(avatarUrl: string) {
    const msgBlock = this.container.createDiv('chat-message-block message-block-ai');
    const avatar = msgBlock.createEl('img', { cls: 'chat-avatar', attr: { src: avatarUrl } });
    const contentContainer = msgBlock.createDiv('chat-message-content message-ai');

    // 1. Tool Actions Container
    const toolContainer = contentContainer.createDiv('chat-tool-actions');

    // 2. Thinking Container
    const thinkingContainer = contentContainer.createDiv('thinking-container');
    thinkingContainer.style.display = 'none';

    // Header with Icon & Text
    const thinkingHeader = thinkingContainer.createDiv('thinking-header');
    setIcon(thinkingHeader.createSpan('thinking-icon'), 'brain-circuit');
    thinkingHeader.createSpan().innerText = 'Thinking Process';

    // Dots Animation (shown while waiting)
    const dotsContainer = thinkingContainer.createDiv('thinking-dots');
    dotsContainer.innerHTML = '<div class="thinking-dot"></div><div class="thinking-dot"></div><div class="thinking-dot"></div>';
    dotsContainer.style.display = 'none';

    // Thinking Content (with scrollable limit)
    const thinkingContent = thinkingContainer.createDiv('thinking-content');
    thinkingContent.style.display = 'none';
    thinkingContent.style.maxHeight = '200px';
    thinkingContent.style.overflowY = 'auto';

    // 3. Response Text Container
    const textContainer = contentContainer.createDiv('chat-text-content');

    // State management for smooth animations
    let fullTextToRender = '';
    let fullThinkingText = '';
    let thinkingTypewriterInterval: any = null;
    let lastThinkingLength = 0;
    let lastTextRenderTime = 0;
    let allActions: ToolAction[] = []; // Accumulate all actions

    const update = async (response: import('../types').ChatResponse, isFinal: boolean = false) => {
      // 1. Render Tool Actions (accumulate them)
      if (response.actions && response.actions.length > 0) {
        // Merge new actions with existing ones
        for (const newAction of response.actions) {
          // Check if this action already exists (by tool name and input)
          const existingIndex = allActions.findIndex(a =>
            a.tool === newAction.tool &&
            JSON.stringify(a.input) === JSON.stringify(newAction.input)
          );

          if (existingIndex >= 0) {
            // Update existing action (e.g., status changed from pending to success)
            allActions[existingIndex] = newAction;
          } else {
            // Add new action
            allActions.push(newAction);
          }
        }

        // Re-render all actions
        toolContainer.empty();
        await this.renderToolActions(toolContainer, allActions);
      }

      // 2. Handle Thinking Block with Typewriter Effect
      if (response.isThinking) {
        thinkingContainer.style.display = 'block';

        if (response.thinkingText && response.thinkingText.length > 0) {
          // We have thinking text - show it with typewriter
          thinkingContent.style.display = 'block';
          dotsContainer.style.display = 'none';

          // Update target thinking text
          fullThinkingText = response.thinkingText;

          // Start typewriter for thinking if not already running
          if (!thinkingTypewriterInterval) {
            thinkingTypewriterInterval = setInterval(() => {
              if (lastThinkingLength < fullThinkingText.length) {
                // Add 3-5 chars per frame for smooth but visible progress
                const charsToAdd = Math.min(5, fullThinkingText.length - lastThinkingLength);
                thinkingContent.innerText = fullThinkingText.substring(0, lastThinkingLength + charsToAdd);
                lastThinkingLength += charsToAdd;
                thinkingContent.scrollTop = thinkingContent.scrollHeight; // Auto-scroll
              } else if (isFinal) {
                // Thinking is complete
                clearInterval(thinkingTypewriterInterval);
                thinkingTypewriterInterval = null;
                thinkingContent.innerText = fullThinkingText;
                thinkingContainer.addClass('thinking-code-block');
              }
            }, 15); // ~67 updates/sec, creates smooth flowing effect
          }
        } else {
          // No thinking text yet - show animated dots
          thinkingContent.style.display = 'none';
          dotsContainer.style.display = 'flex';
        }
      } else {
        // Not thinking anymore - hide the container if no thinking text was produced
        if (!response.thinkingText || response.thinkingText.length === 0) {
          thinkingContainer.style.display = 'none';
        } else {
          // Ensure final thinking text is displayed and styled
          if (thinkingTypewriterInterval) {
            clearInterval(thinkingTypewriterInterval);
            thinkingTypewriterInterval = null;
          }
          thinkingContent.innerText = response.thinkingText;
          thinkingContainer.addClass('thinking-code-block');
          dotsContainer.style.display = 'none';
        }
      }

      // 3. Handle Response Text with Debounced Markdown Rendering
      if (response.text && response.text !== fullTextToRender) {
        fullTextToRender = response.text;

        // Render markdown with debounce to avoid too many DOM updates
        const now = Date.now();
        if (isFinal || (now - lastTextRenderTime > 100)) {
          const tempContainer = createDiv();
          const component = new Component();
          component.load();
          await MarkdownRenderer.render(this.app, fullTextToRender, tempContainer, '', component);

          textContainer.empty();
          while (tempContainer.firstChild) {
            textContainer.appendChild(tempContainer.firstChild);
          }
        }
        lastTextRenderTime = now;
      }

      // 4. Handle Auto-Model Footer Chip
      if (response.acceptedModelId) {
        let footerEl = contentContainer.querySelector('.model-footer-chip') as HTMLElement;
        if (!footerEl) {
          footerEl = contentContainer.createDiv('model-footer-chip');
        }

        // Only show if we differ from the requested model, or just always show for clarity?
        // User requested: "while in auto mode... should have a chip at the bottom"
        // We can just show it if provided.
        footerEl.innerText = `Generated by ${response.acceptedModelId}`;
        footerEl.title = "This model was automatically selected based on your prompt complexity.";
        footerEl.style.display = 'block';
      }

      this.scrollBottom();
    };

    return { container: contentContainer, update };
  }

  async renderToolActions(container: HTMLElement, actions: ToolAction[]) {
    // Ensure container exists (it might be passed from update loop)
    if (!container) return;
    const actionContainer = container.createDiv('chat-tool-actions');

    for (const action of actions) {
      const toolCard = actionContainer.createDiv('tool-action-card');
      if (action.status === 'error') toolCard.addClass('tool-error');
      if (action.status === 'success') toolCard.addClass('tool-success');
      if (action.status === 'pending') toolCard.addClass('tool-pending');


      // Header
      const header = toolCard.createDiv('tool-header');
      const iconSpan = header.createSpan('tool-icon');
      if (action.tool === 'run_terminal_command') {
        setIcon(iconSpan, 'terminal-square');
      } else if (action.tool === 'fetch_url') {
        setIcon(iconSpan, 'link');
      } else if (action.tool === 'google_search_retrieval') { // Internal name for grounding tool often varies
        setIcon(iconSpan, 'globe');
      } else if (action.tool === 'generate_image') {
        setIcon(iconSpan, 'palette');
      } else if (action.tool === 'read_file') {
        setIcon(iconSpan, 'file-text');
      } else if (action.tool === 'search_content') {
        setIcon(iconSpan, 'search');
      } else if (action.tool === 'create_note') {
        setIcon(iconSpan, 'file-plus');
      } else if (action.tool === 'list_files') {
        setIcon(iconSpan, 'files');
      } else if (action.tool === 'list_directory') {
        setIcon(iconSpan, 'folder');
      } else if (action.tool === 'delete_file') {
        setIcon(iconSpan, 'trash');
      } else {
        setIcon(iconSpan, 'wrench'); // Default icon
      }

      const title = header.createSpan('tool-name');
      const statusText = action.status === 'pending' ? 'Using' : 'Used';
      title.innerText = `${statusText} ${action.tool}`;

      // Details (Collapsible? For now just simple line)
      const details = toolCard.createDiv('tool-details');
      if (action.tool === 'generate_image') {
        // Special handling for image generation display?
        // The image link comes in the 'result' usually or formatted text.
        // Just show input prompt here.
        details.innerText = `Prompt: "${action.input.prompt}"`;
      } else if (action.tool === 'create_note' || action.tool === 'read_file') {
        details.innerText = action.input.path;
      } else if (action.tool === 'search_content') {
        details.innerText = `"${action.input.query}"`;
      } else if (action.tool === 'run_terminal_command') {
        details.createEl('code', { text: action.input.command, cls: 'tool-input-code' });
      } else if (action.tool === 'fetch_url') {
        details.innerText = action.input.url;
      } else {
        details.innerText = JSON.stringify(action.input);
      }
    }
  }

  renderThinking(container: HTMLElement) {
    const thinkingContainer = container.createDiv('thinking-container');
    thinkingContainer.innerHTML = '<div class="thinking-dots"><div class="thinking-dot"></div><div class="thinking-dot"></div><div class="thinking-dot"></div></div>';
    this.scrollBottom();
    return thinkingContainer;
  }

  private scrollBottom() {
    this.container.scrollTop = this.container.scrollHeight;
  }
}
