import { App, MarkdownRenderer, Component, setIcon } from 'obsidian';
import { ToolAction } from '../types';

export class MessageRenderer {
  app: App;
  container: HTMLElement;

  constructor(app: App, container: HTMLElement) {
    this.app = app;
    this.container = container;
  }

  renderTo(container: HTMLElement) {
    this.container = container; // Allow rebinding
  }

  async renderUserMessage(msg: import('../types').ChatMessage, avatarUrl: string) {
    const text = msg.parts?.[0]?.text || '';
    const msgBlock = this.container.createDiv('chat-message-block message-block-user');
    const avatar = msgBlock.createEl('img', { cls: 'chat-avatar', attr: { src: avatarUrl } });
    const msgEl = msgBlock.createDiv('chat-message message-user');
    msgEl.innerText = text;
    this.scrollBottom();
    return msgEl;
  }

  async renderAIMessage(msg: import('../types').ChatMessage, avatarUrl: string) {
    const msgBlock = this.container.createDiv('chat-message-block message-block-ai');
    msgBlock.dataset.role = 'model';

    const avatar = msgBlock.createEl('img', { cls: 'chat-avatar', attr: { src: avatarUrl } });
    const contentContainer = msgBlock.createDiv('chat-message-content message-ai');

    // 1. Status Chip (Live Status Indicator)
    const statusChip = contentContainer.createDiv('chat-status-chip');
    statusChip.style.display = 'none'; // Hidden by default until we have state

    // 2. Agent Activity Log (Unified Tools & Thinking)
    const activityLog = contentContainer.createDiv('agent-activity-log');
    activityLog.style.display = 'none'; // Hidden default

    // Header for log (toggle)
    const logHeader = activityLog.createDiv('activity-log-header');
    setIcon(logHeader.createSpan('activity-log-icon'), 'terminal-square');
    logHeader.createSpan({ text: 'Activity Log', cls: 'activity-log-title' });
    logHeader.onclick = () => activityLog.classList.toggle('collapsed');

    const logContent = activityLog.createDiv('activity-log-content');

    // Render Initial Content
    await this.updateActivityLog(activityLog, msg);

    // 3. Response Text
    const textContainer = contentContainer.createDiv('chat-text-content');
    const text = msg.parts?.[0]?.text || '';
    if (text) {
      const component = new Component();
      component.load();
      await MarkdownRenderer.render(this.app, text, textContainer, '', component);
    }

    // 4. Model Chip
    const footerEl = contentContainer.createDiv('model-footer-chip');
    if (msg.model) {
      footerEl.innerText = `Generated by ${msg.model}`;
      footerEl.style.display = 'block';
    } else {
      footerEl.style.display = 'none';
    }

    this.scrollBottom();
    return contentContainer;
  }

  /**
   * Updates an existing message DOM element with new data (Streaming).
   */
  async updateMessage(dom: HTMLElement, msg: import('../types').ChatMessage, avatarUrl: string) {
    // 0. Update Avatar
    const avatar = dom.querySelector('.chat-avatar') as HTMLImageElement;
    if (avatar && avatar.src !== avatarUrl) {
      avatar.src = avatarUrl;
    }

    const contentContainer = dom.querySelector('.chat-message-content') as HTMLElement;
    if (!contentContainer) return;

    // 1. Update Activity Log
    let activityLog = contentContainer.querySelector('.agent-activity-log') as HTMLElement;
    if (!activityLog) {
      // Create if missing (migration/safety)
      // ... (This would be complex to inject mid-stream if structure changed, assuming renderAIMessage called first usually)
    } else {
      await this.updateActivityLog(activityLog, msg);
    }

    // 2. Status Chip Update
    const statusChip = contentContainer.querySelector('.chat-status-chip') as HTMLElement;
    if (statusChip) {
      this.updateStatusChip(statusChip, msg);
    }

    // 3. Text Content
    let textContainer = contentContainer.querySelector('.chat-text-content') as HTMLElement;
    if (!textContainer) textContainer = contentContainer.createDiv('chat-text-content');

    const text = msg.parts?.[0]?.text || '';
    if (textContainer.innerText !== text) {
      const component = new Component();
      component.load();
      textContainer.empty();
      await MarkdownRenderer.render(this.app, text, textContainer, '', component);
      this.scrollBottom();
    }

    // 4. Model Chip
    let footerEl = contentContainer.querySelector('.model-footer-chip') as HTMLElement;
    if (!footerEl) footerEl = contentContainer.createDiv('model-footer-chip');
    if (msg.model) {
      footerEl.innerText = `Generated by ${msg.model}`;
      footerEl.style.display = 'block';
    }
  }

  updateStatusChip(chip: HTMLElement, msg: import('../types').ChatMessage) {
    // Logic to determine what to show
    // Priority: Tool Pending > Thinking > Text Generating

    const isGenerating = true; // We assume this is called during generation mostly, or we check state?
    // Ideally we'd pass isGenerating flag.
    // For now, infer from content.

    let statusText = "";
    let isVisible = false;

    // Check for pending tools
    const pendingTool = msg.actions?.find(a => a.status === 'pending');
    if (pendingTool) {
      statusText = `Using Tool: ${pendingTool.tool}...`;
      isVisible = true;
      chip.addClass('pulsing');
    } else if (msg.thinking && !msg.parts?.[0]?.text) {
      // Thinking and no text yet
      statusText = "Thinking...";
      isVisible = true;
      chip.addClass('pulsing');
    } else if (msg.parts?.[0]?.text && msg.parts[0].text.length < 50) {
      // Short text, maybe just started
      // statusText = "Typing...";
      // isVisible = true;
      chip.removeClass('pulsing');
    } else {
      // Done or long text
      chip.removeClass('pulsing');
      isVisible = false;
    }

    if (isVisible) {
      chip.innerText = statusText;
      chip.style.display = 'inline-flex';
    } else {
      chip.style.display = 'none';
    }
  }

  async updateActivityLog(logContainer: HTMLElement, msg: import('../types').ChatMessage) {
    const content = logContainer.querySelector('.activity-log-content') as HTMLElement;
    if (!content) return;

    // Determine visibility
    const hasContent = (msg.actions && msg.actions.length > 0) || !!msg.thinking;
    if (hasContent) {
      logContainer.style.display = 'block';
    } else {
      logContainer.style.display = 'none';
      return;
    }

    // Render Tools
    // We'll just clear and re-render the list for implementation speed/safety,
    // unless we want to do precise diffing.
    // Since tools are relatively few, re-rendering logic is okay if we don't flash.
    // Better: Re-use renderToolActions but adapted for log items.

    content.empty(); // Simple wipe for now.
    // Note: This kills selection/scroll position in the log.
    // If thinking text is long, this is bad for streaming "Thinking".
    // We should separate "Thoughts" and "Actions".

    if (msg.actions) {
      for (const action of msg.actions) {
        const item = content.createDiv('log-entry tool-entry');
        if (action.status === 'pending') item.addClass('pending');
        if (action.status === 'error') item.addClass('error');

        const icon = item.createSpan('log-icon');
        setIcon(icon, 'wrench');
        item.createSpan({ text: `Used ${action.tool}`, cls: 'log-text' });

        // If output exists, maybe show a snippet?
        // For now keep it one-line summary unless expanded.
      }
    }

    if (msg.thinking) {
      const item = content.createDiv('log-entry thought-entry');
      const icon = item.createSpan('log-icon');
      setIcon(icon, 'brain-circuit');

      const textEl = item.createDiv('log-text thinking-text');
      textEl.innerText = msg.thinking; // This will grow
      // Typewriter: If this is the active thing, scrolling is automatic by browser usually if at bottom
    }
  }

  updateStatus(dom: HTMLElement, status: string | null) {
    const contentContainer = dom.querySelector('.chat-message-content') as HTMLElement;
    if (!contentContainer) return;

    let statusChip = contentContainer.querySelector('.chat-status-chip') as HTMLElement;

    if (!status) {
      if (statusChip) statusChip.remove();
      return;
    }

    if (!statusChip) {
      statusChip = contentContainer.createDiv('chat-status-chip');
      // Insert effectively at bottom (before model chip if any)
      const modelChip = contentContainer.querySelector('.model-footer-chip');
      if (modelChip) {
        contentContainer.insertBefore(statusChip, modelChip);
      } else {
        contentContainer.appendChild(statusChip);
      }
    }

    statusChip.innerText = status;
    // Ensure specific style for visibility
    statusChip.style.display = 'block';
  }



  startAIMessage(avatarUrl: string) {
    const msgBlock = this.container.createDiv('chat-message-block message-block-ai');
    const avatar = msgBlock.createEl('img', { cls: 'chat-avatar', attr: { src: avatarUrl } });
    const contentContainer = msgBlock.createDiv('chat-message-content message-ai');

    // 1. Tool Actions Container
    const toolContainer = contentContainer.createDiv('chat-tool-actions');

    // 2. Thinking Container
    const thinkingContainer = contentContainer.createDiv('thinking-container');
    thinkingContainer.style.display = 'none';

    // Header with Icon & Text
    const thinkingHeader = thinkingContainer.createDiv('thinking-header');
    setIcon(thinkingHeader.createSpan('thinking-icon'), 'brain-circuit');
    thinkingHeader.createSpan().innerText = 'Thinking Process';

    // Dots Animation (shown while waiting)
    const dotsContainer = thinkingContainer.createDiv('thinking-dots');
    dotsContainer.innerHTML = '<div class="thinking-dot"></div><div class="thinking-dot"></div><div class="thinking-dot"></div>';
    dotsContainer.style.display = 'none';

    // Thinking Content (with scrollable limit)
    const thinkingContent = thinkingContainer.createDiv('thinking-content');
    thinkingContent.style.display = 'none';
    thinkingContent.style.maxHeight = '200px';
    thinkingContent.style.overflowY = 'auto';

    // 3. Response Text Container
    const textContainer = contentContainer.createDiv('chat-text-content');

    // State management for smooth animations
    let fullTextToRender = '';
    let fullThinkingText = '';
    let thinkingTypewriterInterval: any = null;
    let lastThinkingLength = 0;
    let lastTextRenderTime = 0;
    let allActions: ToolAction[] = []; // Accumulate all actions

    const update = async (response: import('../types').ChatResponse, isFinal: boolean = false) => {
      // 1. Render Tool Actions (accumulate them)
      if (response.actions && response.actions.length > 0) {
        // Merge new actions with existing ones
        for (const newAction of response.actions) {
          // Check if this action already exists (by tool name and input)
          const existingIndex = allActions.findIndex(a =>
            a.tool === newAction.tool &&
            JSON.stringify(a.input) === JSON.stringify(newAction.input)
          );

          if (existingIndex >= 0) {
            // Update existing action (e.g., status changed from pending to success)
            allActions[existingIndex] = newAction;
          } else {
            // Add new action
            allActions.push(newAction);
          }
        }

        // Re-render all actions
        toolContainer.empty();
        await this.renderToolActions(toolContainer, allActions);
      }

      // 2. Handle Thinking Block with Typewriter Effect
      if (response.isThinking) {
        thinkingContainer.style.display = 'block';

        if (response.thinkingText && response.thinkingText.length > 0) {
          // We have thinking text - show it with typewriter
          thinkingContent.style.display = 'block';
          dotsContainer.style.display = 'none';

          // Update target thinking text
          fullThinkingText = response.thinkingText;

          // Start typewriter for thinking if not already running
          if (!thinkingTypewriterInterval) {
            thinkingTypewriterInterval = setInterval(() => {
              if (lastThinkingLength < fullThinkingText.length) {
                // Add 3-5 chars per frame for smooth but visible progress
                const charsToAdd = Math.min(5, fullThinkingText.length - lastThinkingLength);
                thinkingContent.innerText = fullThinkingText.substring(0, lastThinkingLength + charsToAdd);
                lastThinkingLength += charsToAdd;
                thinkingContent.scrollTop = thinkingContent.scrollHeight; // Auto-scroll
              } else if (isFinal) {
                // Thinking is complete
                clearInterval(thinkingTypewriterInterval);
                thinkingTypewriterInterval = null;
                thinkingContent.innerText = fullThinkingText;
                thinkingContainer.addClass('thinking-code-block');
              }
            }, 15); // ~67 updates/sec, creates smooth flowing effect
          }
        } else {
          // No thinking text yet - show animated dots
          thinkingContent.style.display = 'none';
          dotsContainer.style.display = 'flex';
        }
      } else {
        // Not thinking anymore - hide the container if no thinking text was produced
        if (!response.thinkingText || response.thinkingText.length === 0) {
          thinkingContainer.style.display = 'none';
        } else {
          // Ensure final thinking text is displayed and styled
          if (thinkingTypewriterInterval) {
            clearInterval(thinkingTypewriterInterval);
            thinkingTypewriterInterval = null;
          }
          thinkingContent.innerText = response.thinkingText;
          thinkingContainer.addClass('thinking-code-block');
          dotsContainer.style.display = 'none';
        }
      }

      // 3. Handle Response Text with Debounced Markdown Rendering
      if (response.text && response.text !== fullTextToRender) {
        fullTextToRender = response.text;

        // Render markdown with debounce to avoid too many DOM updates
        const now = Date.now();
        if (isFinal || (now - lastTextRenderTime > 100)) {
          const tempContainer = createDiv();
          const component = new Component();
          component.load();
          await MarkdownRenderer.render(this.app, fullTextToRender, tempContainer, '', component);

          textContainer.empty();
          while (tempContainer.firstChild) {
            textContainer.appendChild(tempContainer.firstChild);
          }
        }
        lastTextRenderTime = now;
      }

      // 4. Handle Auto-Model Footer Chip
      if (response.acceptedModelId) {
        let footerEl = contentContainer.querySelector('.model-footer-chip') as HTMLElement;
        if (!footerEl) {
          footerEl = contentContainer.createDiv('model-footer-chip');
        }

        // Only show if we differ from the requested model, or just always show for clarity?
        // User requested: "while in auto mode... should have a chip at the bottom"
        // We can just show it if provided.
        footerEl.innerText = `Generated by ${response.acceptedModelId}`;
        footerEl.title = "This model was automatically selected based on your prompt complexity.";
        footerEl.style.display = 'block';
      }

      this.scrollBottom();
    };

    return { container: contentContainer, update };
  }

  async renderToolActions(container: HTMLElement, actions: ToolAction[]) {
    // Ensure container exists (it might be passed from update loop)
    if (!container) return;
    const actionContainer = container.createDiv('chat-tool-actions');

    for (const action of actions) {
      const toolCard = actionContainer.createDiv('tool-action-card');
      if (action.status === 'error') toolCard.addClass('tool-error');
      if (action.status === 'success') toolCard.addClass('tool-success');
      if (action.status === 'pending') toolCard.addClass('tool-pending');


      // Header
      const header = toolCard.createDiv('tool-header');
      const iconSpan = header.createSpan('tool-icon');
      if (action.tool === 'run_terminal_command') {
        setIcon(iconSpan, 'terminal-square');
      } else if (action.tool === 'fetch_url') {
        setIcon(iconSpan, 'link');
      } else if (action.tool === 'google_search_retrieval') { // Internal name for grounding tool often varies
        setIcon(iconSpan, 'globe');
      } else if (action.tool === 'generate_image') {
        setIcon(iconSpan, 'palette');
      } else if (action.tool === 'read_file') {
        setIcon(iconSpan, 'file-text');
      } else if (action.tool === 'search_content') {
        setIcon(iconSpan, 'search');
      } else if (action.tool === 'create_note') {
        setIcon(iconSpan, 'file-plus');
      } else if (action.tool === 'list_files') {
        setIcon(iconSpan, 'files');
      } else if (action.tool === 'list_directory') {
        setIcon(iconSpan, 'folder');
      } else if (action.tool === 'delete_file') {
        setIcon(iconSpan, 'trash');
      } else {
        setIcon(iconSpan, 'wrench'); // Default icon
      }

      const title = header.createSpan('tool-name');
      const statusText = action.status === 'pending' ? 'Using' : 'Used';
      title.innerText = `${statusText} ${action.tool}`;

      // Details (Collapsible? For now just simple line)
      const details = toolCard.createDiv('tool-details');
      if (action.tool === 'generate_image') {
        // Special handling for image generation display?
        // The image link comes in the 'result' usually or formatted text.
        // Just show input prompt here.
        details.innerText = `Prompt: "${action.input.prompt}"`;
      } else if (action.tool === 'create_note' || action.tool === 'read_file') {
        details.innerText = action.input.path;
      } else if (action.tool === 'search_content') {
        details.innerText = `"${action.input.query}"`;
      } else if (action.tool === 'run_terminal_command') {
        details.createEl('code', { text: action.input.command, cls: 'tool-input-code' });
      } else if (action.tool === 'fetch_url') {
        details.innerText = action.input.url;
      } else {
        details.innerText = JSON.stringify(action.input);
      }
    }
  }

  renderThinking(container: HTMLElement) {
    const thinkingContainer = container.createDiv('thinking-container');
    thinkingContainer.innerHTML = '<div class="thinking-dots"><div class="thinking-dot"></div><div class="thinking-dot"></div><div class="thinking-dot"></div></div>';
    this.scrollBottom();
    return thinkingContainer;
  }

  private scrollBottom() {
    this.container.scrollTop = this.container.scrollHeight;
  }
}
